//常量库
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const SUCCESS_GET_SNSLOGINS = 'SUCCESS_GET_SNSLOGINS'
export const FAILURE_GET_SNSLOGINS = 'FAILURE_GET_SNSLOGINS'